Windows:
  arch_graph_path : C:\Users\t26607bb\Desktop\graph_zcu9eg
  Data_path       : C:\Users\t26607bb\Desktop\CPS_Project\Path_Search\Data_xczu9eg

Linux:
  arch_graph_path : /home/bardia/Desktop/bardia/Architecture Graph/ZCU9EG
  Data_path       : /home/bardia/Desktop/bardia/ManAge_Data/Data_xczu9eg