set_property LOC SLICE_X69Y90 [get_cells RO[0].LUT6_inst]
set_property BEL F6LUT [get_cells RO[0].LUT6_inst]
set_property LOC SLICE_X69Y90 [get_cells RO[1].LUT6_inst]
set_property BEL D6LUT [get_cells RO[1].LUT6_inst]
set_property LOC SLICE_X68Y90 [get_cells RO[2].LUT6_inst]
set_property BEL C6LUT [get_cells RO[2].LUT6_inst]
set_property LOC SLICE_X68Y90 [get_cells RO[3].LUT6_inst]
set_property BEL D6LUT [get_cells RO[3].LUT6_inst]
set_property LOC SLICE_X69Y90 [get_cells RO[4].LUT6_inst]
set_property BEL A6LUT [get_cells RO[4].LUT6_inst]
set_property LOC SLICE_X68Y90 [get_cells RO[5].LUT6_inst]
set_property BEL H6LUT [get_cells RO[5].LUT6_inst]
set_property LOC SLICE_X69Y90 [get_cells RO[6].LUT6_inst]
set_property BEL B6LUT [get_cells RO[6].LUT6_inst]
set_property LOC SLICE_X68Y90 [get_cells RO[7].LUT6_inst]
set_property BEL E6LUT [get_cells RO[7].LUT6_inst]
set_property LOC SLICE_X68Y90 [get_cells RO[8].LUT6_inst]
set_property BEL G6LUT [get_cells RO[8].LUT6_inst]
set_property LOC SLICE_X69Y90 [get_cells RO[9].LUT6_inst]
set_property BEL C6LUT [get_cells RO[9].LUT6_inst]
set_property LOC SLICE_X69Y90 [get_cells RO[10].LUT6_inst]
set_property BEL H6LUT [get_cells RO[10].LUT6_inst]
set_property LOC SLICE_X68Y90 [get_cells RO[11].LUT6_inst]
set_property BEL F6LUT [get_cells RO[11].LUT6_inst]
set_property LOC SLICE_X69Y90 [get_cells RO[12].LUT6_inst]
set_property BEL E6LUT [get_cells RO[12].LUT6_inst]
set_property LOC SLICE_X68Y90 [get_cells RO[13].LUT6_inst]
set_property BEL A6LUT [get_cells RO[13].LUT6_inst]
set_property LOC SLICE_X69Y90 [get_cells RO[14].LUT6_inst]
set_property BEL G6LUT [get_cells RO[14].LUT6_inst]
set_property LOC SLICE_X68Y90 [get_cells RO[15].LUT6_inst]
set_property BEL B6LUT [get_cells RO[15].LUT6_inst]

set_property FIXED_ROUTE {CLE_CLE_L_SITE_0_F_O INT_NODE_IMUX_21_INT_OUT1 BYPASS_E12 INT_NODE_IMUX_13_INT_OUT0 IMUX_E35} [get_nets O6[0]]
set_property FIXED_ROUTE {CLE_CLE_L_SITE_0_D_O INT_NODE_IMUX_13_INT_OUT1 BYPASS_E6 INT_NODE_IMUX_31_INT_OUT0 IMUX_E21} [get_nets O6[1]]
set_property FIXED_ROUTE {CLE_CLE_M_SITE_0_C_O INT_NODE_IMUX_63_INT_OUT0 IMUX_W20} [get_nets O6[2]]
set_property FIXED_ROUTE {CLE_CLE_M_SITE_0_D_O INT_NODE_IMUX_45_INT_OUT1 BYPASS_W6 INT_NODE_IMUX_63_INT_OUT0 IMUX_W21} [get_nets O6[3]]
set_property FIXED_ROUTE {CLE_CLE_L_SITE_0_A_O INT_NODE_SDQ_22_INT_OUT1 INT_INT_SDQ_72_INT_OUT0 INT_NODE_GLOBAL_11_INT_OUT1 INT_NODE_IMUX_11_INT_OUT0 IMUX_E18} [get_nets O6[4]]
set_property FIXED_ROUTE {CLE_CLE_M_SITE_0_H_O INT_NODE_IMUX_58_INT_OUT0 IMUX_W47} [get_nets O6[5]]
set_property FIXED_ROUTE {CLE_CLE_L_SITE_0_B_O INT_NODE_IMUX_8_INT_OUT1 BYPASS_E6 INT_NODE_IMUX_1_INT_OUT1 IMUX_E19} [get_nets O6[6]]
set_property FIXED_ROUTE {CLE_CLE_M_SITE_0_E_O INT_NODE_IMUX_36_INT_OUT1 BYPASS_W3 INT_NODE_IMUX_42_INT_OUT0 IMUX_W34} [get_nets O6[7]]
set_property FIXED_ROUTE {CLE_CLE_M_SITE_0_G_O INT_NODE_IMUX_49_INT_OUT1 BYPASS_W9 INT_NODE_IMUX_56_INT_OUT0 IMUX_W46} [get_nets O6[8]]
set_property FIXED_ROUTE {CLE_CLE_L_SITE_0_C_O INT_NODE_IMUX_31_INT_OUT0 IMUX_E20} [get_nets O6[9]]
set_property FIXED_ROUTE {CLE_CLE_L_SITE_0_H_O INT_NODE_IMUX_26_INT_OUT0 IMUX_E47} [get_nets O6[10]]
set_property FIXED_ROUTE {CLE_CLE_M_SITE_0_F_O INT_NODE_IMUX_53_INT_OUT1 BYPASS_W12 INT_NODE_IMUX_45_INT_OUT0 IMUX_W35} [get_nets O6[11]]
set_property FIXED_ROUTE {CLE_CLE_L_SITE_0_E_O INT_NODE_IMUX_4_INT_OUT1 BYPASS_E3 INT_NODE_IMUX_10_INT_OUT0 IMUX_E34} [get_nets O6[12]]
set_property FIXED_ROUTE {CLE_CLE_M_SITE_0_A_O INT_NODE_SDQ_70_INT_OUT1 INT_INT_SDQ_60_INT_OUT1 INT_NODE_SDQ_1_INT_OUT0 INT_INT_SDQ_72_INT_OUT0 INT_NODE_IMUX_43_INT_OUT0 IMUX_W18} [get_nets O6[13]]
set_property FIXED_ROUTE {CLE_CLE_L_SITE_0_G_O INT_NODE_IMUX_17_INT_OUT1 BYPASS_E9 INT_NODE_IMUX_24_INT_OUT0 IMUX_E46} [get_nets O6[14]]
set_property FIXED_ROUTE {CLE_CLE_M_SITE_0_B_O INT_NODE_IMUX_40_INT_OUT1 BYPASS_W6 INT_NODE_IMUX_33_INT_OUT1 IMUX_W19} [get_nets O6[15]]
